server:
  port: 2007
  context-path: /boot-vue

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_bootbucket?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp